name: Deploy and Build/Run App on Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
    - name: Install rsync
      run: sudo apt-get install -y rsync
  
    - name: Copy files via rsync
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ azureuser@${{ secrets.REMOTE_SERVER_IP }}:/home/azureuser/mawruth-image-classification

  build-and-run:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute build and run commands
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.REMOTE_SERVER_IP }} 'cd /home/azureuser/mawruth-image-classification && make install-requirements && make set-envs && make run'
